/*
  Ältere SoundCloud-Releases (vor 2026) — die 9 aktuellen Releases, die auch
  auf SoundCloud liegen, laufen bereits nativ im Haupt-Player und sind hier
  bewusst ausgeschlossen, damit das Archiv wirklich nur vor-2026-Material zeigt.

  Vollständige Liste aller 94 Tracks des Profils, live per Browser von
  soundcloud.com/audiohabitatrec/tracks geladen (nicht per curl/statischem
  Fetch — SoundCloud lädt die Trackliste per JS nach, ein einfacher HTML-
  Abruf sieht sie gar nicht). Minus die 9 aktuellen Tracks bleiben 85 hier im
  Archiv.
*/

var SOUNDCLOUD_ARCHIVE = [
  { title: "Audio Habitat Beer Bottle", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-beer-bottle" },
  { title: "Audio Habitat Election", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-election" },
  { title: "Audio Habitat Stay Out", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-stay-out" },
  { title: "Audio Habitat VSL", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-vsl" },
  { title: "Metro (VIP)", url: "https://soundcloud.com/audiohabitatrec/metro-vip" },
  { title: "DNBPodcast No.1 2016 with Audio Habitat (Free Download)", url: "https://soundcloud.com/audiohabitatrec/dnbpodcast-no1-2016-with-audio-habitat-free-download" },
  { title: "(6) Rise / Function Records \"Synthesis Collaboration Album\"", url: "https://soundcloud.com/audiohabitatrec/6-rise-funktion-records-synthesis-collaboration-album" },
  { title: "District (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/district-original-mix" },
  { title: "Everything Butt (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/everything-butt-original-mix" },
  { title: "Frontside (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/frontside-original-mix" },
  { title: "Plasma (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/plasma-original-mix" },
  { title: "Croatoan (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/croatoan-original-mix" },
  { title: "The Opening (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/the-opening-original-mix" },
  { title: "Code 8 (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/code-8-original-mix" },
  { title: "Level 7 (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/level-7-original-mix" },
  { title: "Model (Original)", url: "https://soundcloud.com/audiohabitatrec/model-original" },
  { title: "Echoes (Original)", url: "https://soundcloud.com/audiohabitatrec/echoes-original" },
  { title: "Problem With", url: "https://soundcloud.com/audiohabitatrec/problem-with" },
  { title: "Layer (Original)", url: "https://soundcloud.com/audiohabitatrec/layer-original" },
  { title: "Raising Sounds", url: "https://soundcloud.com/audiohabitatrec/raising-sounds" },
  { title: "Multifunktion", url: "https://soundcloud.com/audiohabitatrec/multifunktion" },
  { title: "The DNB Advents Calendar 2014 (mixed) Free Download", url: "https://soundcloud.com/audiohabitatrec/advents-calendar-2014-mix-free-download" },
  { title: "024 - Streaming Out (2008)", url: "https://soundcloud.com/audiohabitatrec/024-streaming-out-2008the-dnb-advent-calendar-2014-free-download" },
  { title: "Elipse (2010)", url: "https://soundcloud.com/audiohabitatrec/elipse-2010the-dnb-advent-calendar-2014-free-download" },
  { title: "022 - Lazy Day (2012)", url: "https://soundcloud.com/audiohabitatrec/022-lazy-day-2012-the-dnb-advent-calendar-2014-free-download" },
  { title: "021 Fragment (2013)", url: "https://soundcloud.com/audiohabitatrec/fragment-2013the-dnb-advent-calendar-2014-free-download" },
  { title: "020 - Know How (2013)", url: "https://soundcloud.com/audiohabitatrec/020-know-how-2013" },
  { title: "019 - All Souls (2013)", url: "https://soundcloud.com/audiohabitatrec/019-all-souls-2013" },
  { title: "018 - Zoom In (2013)", url: "https://soundcloud.com/audiohabitatrec/018-zoom-in-2013" },
  { title: "017 - Audiobots (2014)", url: "https://soundcloud.com/audiohabitatrec/017-audiobots-2014" },
  { title: "016 - Drained (2014 EdiT)", url: "https://soundcloud.com/audiohabitatrec/016-drained-2014-edit-2014" },
  { title: "015 - Twister (2009)", url: "https://soundcloud.com/audiohabitatrec/015-twister-2009" },
  { title: "014 - Analog Depature (2012)", url: "https://soundcloud.com/audiohabitatrec/014-analog-depature-2012" },
  { title: "013 - Rootkit (2013)", url: "https://soundcloud.com/audiohabitatrec/013-rootkit-2013" },
  { title: "011 - Lets R.O.C (2012)", url: "https://soundcloud.com/audiohabitatrec/011-lets-r-o-c-2012" },
  { title: "010 - Sound is Rumble (2013)", url: "https://soundcloud.com/audiohabitatrec/010-sound-is-rumble-2013" },
  { title: "009 - Sticks (2013)", url: "https://soundcloud.com/audiohabitatrec/009-sticks-2013" },
  { title: "008 - Glow (2013)", url: "https://soundcloud.com/audiohabitatrec/008-glow-2013" },
  { title: "Under Pressure (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/under-pressure-original-mix" },
  { title: "Twelve Minds (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/twelve-minds-original-mix" },
  { title: "Parameter (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/parameter-original-mix" },
  { title: "Technical Shit (Original Mix)", url: "https://soundcloud.com/audiohabitatrec/technical-shit-original-mix" },
  { title: "006 - Too Far (2013)", url: "https://soundcloud.com/audiohabitatrec/006-too-far-2013" },
  { title: "005 - F…yourself (2013)", url: "https://soundcloud.com/audiohabitatrec/005-f-yourself-2013" },
  { title: "004 - Gypsy (2013)", url: "https://soundcloud.com/audiohabitatrec/004-gypsy-2013" },
  { title: "003 - Testosteron (2013)", url: "https://soundcloud.com/audiohabitatrec/003-testosteron-2013" },
  { title: "002 - Hurt (2010)", url: "https://soundcloud.com/audiohabitatrec/002-hurt-2010" },
  { title: "001 - Isotope (2012)", url: "https://soundcloud.com/audiohabitatrec/001-isotope-2012" },
  { title: "Safra - Change (Audio Habitat Remix) FREE DOWNLOAD", url: "https://soundcloud.com/audiohabitatrec/safra-change-audio-habitat-remix-free-download" },
  { title: "Dom & Roland - Get Up (Audio Habitat Remix)", url: "https://soundcloud.com/audiohabitatrec/dom-roland-get-up-audio-habitat-remix" },
  { title: "Audio Habitat Podcast September 2014", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-podcast-september-2014" },
  { title: "Black Sun Empire & Nymfo - Kempi (Remix II)", url: "https://soundcloud.com/audiohabitatrec/black-sun-empire-nymfo-kempi-remix-ii" },
  { title: "Audio Habitat Podcast August 2014", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-podcast-august-test" },
  { title: "Maintain // forthcoming on Dispatch Recordings // MOS Radio Show", url: "https://soundcloud.com/audiohabitatrec/maintain-forthcoming-on-dispatch-recordings-mos-radio-show" },
  { title: "DCUK0014- Command Strange - Come On (Audio Habitat Remix)", url: "https://soundcloud.com/audiohabitatrec/dcuk0014-come-on-audio-habitat-remix" },
  { title: "Hound SRBEDIGI024", url: "https://soundcloud.com/audiohabitatrec/hound-srbedigi024" },
  { title: "Audio Habitat - 30min Mini Mix - 06.2014 - Dub Selection", url: "https://soundcloud.com/audiohabitatrec/30min-mini-mix-062014" },
  { title: "BBC Radio // Crissy Criss 1Xtra Show 14.05.2014 - Audio Habitat - Lox (on Directors Cut)", url: "https://soundcloud.com/audiohabitatrec/bbc-radio-crissy-criss-1xtra-show-14052014-audio-habitat-lox-on-directors-cut" },
  { title: "Audio Habitat Podcast May 2014", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-podcast-may-2014" },
  { title: "Smooth Trip - Instrumental \"Preview 2014\"", url: "https://soundcloud.com/audiohabitatrec/smooth-trip-instrumental" },
  { title: "Melt Down \"Forthcoming on SRBE \"", url: "https://soundcloud.com/audiohabitatrec/melt-down-preview-unsigned" },
  { title: "Back into Time", url: "https://soundcloud.com/audiohabitatrec/back-into-time" },
  { title: "D_Droid", url: "https://soundcloud.com/audiohabitatrec/d_droid" },
  { title: "Fine Arts", url: "https://soundcloud.com/audiohabitatrec/fine-arts" },
  { title: "Hydroxid", url: "https://soundcloud.com/audiohabitatrec/hydroxid" },
  { title: "Influenz", url: "https://soundcloud.com/audiohabitatrec/influenz" },
  { title: "Kalaidon", url: "https://soundcloud.com/audiohabitatrec/kalaidon" },
  { title: "Roc it up", url: "https://soundcloud.com/audiohabitatrec/roc-it-up" },
  { title: "The Eagle has landet", url: "https://soundcloud.com/audiohabitatrec/the-eagle-has-landet" },
  { title: "The Pianist", url: "https://soundcloud.com/audiohabitatrec/the-pianist" },
  { title: "Unknown ID", url: "https://soundcloud.com/audiohabitatrec/unknown-id" },
  { title: "Mr. Probz - Waves (Audio Habitat Bootleg _ Tribute Remix)", url: "https://soundcloud.com/audiohabitatrec/mr-probz-waves-audio-habitat" },
  { title: "Audio Habitat - Promotion Mix 2014 (A Selection of the forthcoming Releases & Unreleased Dub´s)", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-promotion-mix" },
  { title: "Linkin Park - New Devide (Audio Habitat Bootleg) / FREE DOWNLOAD", url: "https://soundcloud.com/audiohabitatrec/new-devide-audio-habitat" },
  { title: "Audio Habitat - Rapid Transportation // Proximity Effect Vol.4 //", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-rapid" },
  { title: "Audio Habitat in the Mix (All Tracks Released in 2013)", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-2013" },
  { title: "Audio Habitat - The King - (2010) Dj SS ReEdit", url: "https://soundcloud.com/audiohabitatrec/the-king-dj-ss-reedit" },
  { title: "The Prototypes - Evolution feat. Darrison (Audio Habitat Remix)", url: "https://soundcloud.com/audiohabitatrec/the-prototypes-evolution-feat-darrison-audio-habitat-remix" },
  { title: "Black Sun Empire & Noisia - Hideous [Audio Habitat Remix] FREE", url: "https://soundcloud.com/audiohabitatrec/black-sun-empire-noisia" },
  { title: "Audio Habitat The Vault & Oxygen & Base Walk & 10 Years Benefit Beats The Vault Ep 2014", url: "https://soundcloud.com/audiohabitatrec/audio-habitat-the-vault-oxygen" },
  { title: "Optiv & BTK - Ignition feat. Ryme Tyme (Audio Habitat Remix) DNBA", url: "https://soundcloud.com/audiohabitatrec/optiv-btk-ignition-too-late" },
  { title: "Phace - Hot Rock (Audio Habitat Remix)", url: "https://soundcloud.com/audiohabitatrec/phace-hot-rock-audio-habitat" },
  { title: "Black Sun Empire & Nymfo - Kempi (Audio Habitat remix)", url: "https://soundcloud.com/audiohabitatrec/kempi_remix_audiohabitat" },
  { title: "Histamin (Original)", url: "https://soundcloud.com/audiohabitatrec/histamin-original" },
  { title: "Kemosite (Original)", url: "https://soundcloud.com/audiohabitatrec/kemosite-original" }
];
